### ISSUE TITLE
`Page.Image.make` optional parameter cannot be erased

### ISSUE THREAD

**Issue by thizanne** [yannham/mechaml#2]
`Page.Image.make` signature is `val make : ?resolver:(Uri.t -> Uri.t) -> source:string -> t`. Due to the absence of any positional parameter, the optional parameter `resolver` isn't actually optional and must be provided.

A fix could either : 
1. Make `resolver` non-optional 👎 
2. Make `source` a positional parameter
3. Add `()` as a positional mandatory parameter at the end, indicating that `resolver` has been either provided or explicitly erased.

Since `source` is the only non-optional parameter of this function, I would suggest solution 2, but I have no strong preference.

**Comment by thizanne** [comment]
(By the way I don't know what `resolver` is supposed to do, that would be worth some doc -- which is easier to say that to actually do).

**Comment by yannham** [comment]
Thanks for reporting. Resolver is a function that turns (possibly) relative URIs of the HTML page to absolute ones, basically if the page's URI is `uri`, resolver is `Uri.resolve "" uri`. If none is given, identity is used. I agree that this should be documented, and fix the parameter problem that also affect `Link.make`.

**Comment by yannham** [comment]
Fixed by 54545212d59f4a35c3fd9c62e7609d42a9c3fbb3. I finally removed these helpers, because it doesn't make a lot of sense for the lib user to build a link or a image : the only available actions are to retrieve the parameters (provided) or to click the link/download the image (but this is easily done directly with the source URI using Agent helpers).
